### PR TITLE
Add more informations to questions

### LINKED ISSUE #20: Add More Information to Questions and Anwers
Some useful information is currently not supported

* `last_activity_date`
* `created_date`
* `view_count` (Questions only)
* `favorite_count` (Questions only)

### PR DESCRIPTION
**Pull request by victorvicari**
Closes #20

make use of `calendar.getInstance()` to set properly the dates. For the favorites, use the star icon created at `drawables` folder.
pic_1_stack_app
pic_2_stack_app

### CODE REVIEW

**Comment by tylerbwong** [comment]
Hey @victorvicari thanks for the PR! I'm actually still not 100% sure if I want to add all of this information to the main feed since it's getting a little crowded. Let's put this on hold for now. I was also hoping we could format the date like "2 years ago" or "2 minutes ago" instead of the full date.

**Comment by victorvicari** [comment]
Sure, I'll take another look at it, as you suggested. And, about item view, yes, I had the same impression.

**Comment by tylerbwong** [comment]
Awesome! Also, I'm in the process of adding favorites in #49 so we probably can remove it from this PR.

**Comment by tylerbwong** [comment]
Closing for now as we revisit how to format question items.

**Pull request closed without merging**
